### ISSUE TITLE
Missing + in download_ckpts.sh

### ISSUE THREAD

**Issue by lokesh12345678910** [ShampooWang/SpeechCLIP_plus#1]
In line 14 of https://github.com/ShampooWang/SpeechCLIP_plus/blob/main/download_ckpts.sh, there's is a plus missing in the bolded part: 

wget https://huggingface.co/ShampooWang/speechclip_plus/resolve/main/large/flickr/hybrid%2B/epoch%3D50-step%3D5966-val_recall_mean_10%3D89.3500.ckpt?download=true -O icassp_sasb_ckpts/SpeechCLIP+/large/flickr/**hybrid**/model.ckpt

**Comment by ShampooWang** [comment]
Thanks for pointing out! I have fixed it.
